#!/usr/bin/env python
# This is a Section_ID Calculator for Gamecube Phantasy Star Online Character Names
import sys

name = input("Provide a name: ")
if len(name) > 12:
    print('Error! Name can only be 12 characters or less')
    sys.exit()

result = sum([ord(char) for char in list(name)]) # Obtain sum of ASCII values with ord()

id_dict = {
0: 'Viridia',
1: 'Greenill',
2: 'Skyly',
3: 'Bluefull',
4: 'Purplenum',
5: 'Pinkal',
6: 'Redria',
7: 'Oran',
8: 'Yellowboze',
9: 'Whitill'}

print(id_dict[int(str(result)[-1])]) # return Section id
