#!/usr/bin/env python
# This is a Section_ID Calculator for Gamecube Phantasy Star Online Character Names
import sys

name = input("Provide a name: ")

result = sum([ord(char) for char in list(name)]) # sum ASCII values

id_dict = {
0: 'Viridia',
1: 'Greenill',
2: 'Skyly',
3: 'Bluefull',
4: 'Purplenum',
5: 'Pinkal',
6: 'Redria',
7: 'Oran',
8: 'Yellowboze',
9: 'Whitill'}

ref = id_dict[int(str(result)[-1])]
error = "Error! Name must be 12 characters or less"
print(ref) if len(name) <=12 else print(error) & sys.exit()
