#!/usr/bin/env python
'''This is a Section_ID Calculator for
Gamecube Phantasy Star Online Character Names'''
import sys

NAME = input("Provide a name: ")
ERROR = "Error! Name must be 12 characters or less"
NAME = NAME if len(NAME) <= 12 else print(ERROR) & sys.exit()

RESULT = sum([ord(char) for char in list(NAME)]) # sum ASCII values

ID_DICT = {
    0: 'Viridia',
    1: 'Greenill',
    2: 'Skyly',
    3: 'Bluefull',
    4: 'Purplenum',
    5: 'Pinkal',
    6: 'Redria',
    7: 'Oran',
    8: 'Yellowboze',
    9: 'Whitill'}

REF = ID_DICT[int(str(RESULT)[-1])]
print(REF)
